gui:
  title: "&8&lDaily Rewards"
  # Available templates: DEFAULT, COMPACT, BORDERED_DAILY, DAILY_REWARDS_PLUS, NDAILY_REWARDS, CUSTOM
  # Read https://dave-12.gitbook.io/activity-rewarder/configuring/gui-and-templates#custom-templates for more info on
  # creating and using templates
  template: "DEFAULT"
  upcoming-reward:
    # Whether the next "large" reward will be shown in the gui
    enabled: true
    # The lore of the upcoming reward (set first line to blank for item's original lore)
    lore:
      - "&7&o- Next large reward"
  # redeemable-name and collected-name can contain %day% which will display the day number related to the tiem
  redeemable-name: "&6Day %day%"
  collected-name: "&6Day %day% - Collected"
  # Display item for the border
  border-item: GRAY_STAINED_GLASS_PANE
  # Display item for when a reward is collected
  collected-item: COAL

# daily-rewards-enabled: Whether the daily rewards module is enabled
daily-rewards-enabled: true
# hourly-rewards-enabled: Whether the hourly rewards module is enabled
hourly-rewards-enabled: true

# The number of days before the reward cycle loops
loop-length: 14
# The length in seconds between reminders being sent
reminder-period: 1800
# Whether a player's days will reset if they miss a day
days-reset: false

# Display items for different reward categories
categories:
  small: GOLD_NUGGET
  medium: GOLD_INGOT
  large: GOLD_BLOCK

messages:
  reload: "&aConfig reloaded"
  reminder: "&e&lRewards &8» &7It looks like you haven't collected today's reward from &e/rewards"
  reward-given: "&e&lRewards &8» &aYou have collected today's reward"
  hourly-bonus-given: "&e&lRewards &8» &7You have received a bonus for playing &e%hours% &7hours"

# Debug Modes: none, hourly, daily, all
debug-mode: none