# Enable or disable specific Activity Rewarder modules
modules:
  daily-rewards: true
  daily-playtime-goals: true
  global-playtime-goals: true

# Whether players will receive all rewards on a day or just the one with the highest priority
allow-reward-stacking: false

# Whether rewards will automatically refresh when the day ticks over
# - This allows the plugin to use much less ram by only storing rewards that could be needed on the specified day
rewards-refresh-daily: true

# The length in seconds between reminders being sent
reminder-period: 1800
# The sound that will be played when a player is sent a reminder
reminder-sound: block_note_block_pling
# Whether a player will reset to day 1 if they miss a day
streak-mode: true

# Display items for different reward categories
categories:
  small:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAxYzYzYzIwM2ExODQxZGUyN2EwZTA5YTI5NWY1Yjg3MzM2MjcwMjRmMTY2OGEwMWQyMDE4NmEzZjg2MzA0MCJ9fX0=
  medium:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjEwMzhjZGM4NDIzNGI1YWZiM2FlYTg1M2JmM2QwNTE3NWQxOWFlN2I0ODc1YTkxYjUyZjc2NmMwN2IzZGIwYiJ9fX0=
  large:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjUyODdhZjk3ZjkzZDM3MTg5NzNmNGUxM2VkMGZhM2E2ZjQzOWU3MmMxNDVmZTRjZDkwMmIwNWMxYzEwYWYxOCJ9fX0=

# Upcoming category to display
upcoming-category: large

# Display item templates
item-templates:
  # Template for default rewards
  default-reward:
    display-name: "<gradient:#CEB5FE:#81BAFE>Day %day%</gradient>"
  # Template for collectable rewards
  redeemable-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmI1N2Y0ODVlOWVjY2E1MzIzNDQ4NTBjNTFhYjQ0ZGQ2YWE1ZDQ1MTRiMzFjNmRmOWZjMjBlMzZiM2E4OWQ4YyJ9fX0=
    display-name: "&#f5e389Day %day% - Redeemable"
    enchanted: true
  # Template for collected rewards
  collected-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZkNTEyY2NlNGU3OTUyOGI2MGIzNWRmZTZmN2JmYzg0M2IyOTY4NDIxMDViMWNkMjY4MjdiNTkwOGIxMzU0ZCJ9fX0=
    display-name: "&#f5e389Day %day% - Collected"
    enchanted: false
  # Template for missed rewards
  missed-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRkMzBhYWMyYTFmMmQxOGM3NzU1Y2ZjYTJiYzYwOWZjMzkxZjQxOTg5YjA2NmNlOTMxNjA3NzY5MDZiZTg1YSJ9fX0=
    display-name: "&7Day %day% &8(Missed)"
  # Template for upcoming reward
  upcoming-reward:
    lore:
      - "&7&o- Upcoming reward"

  # Template for border items - more items can be created like this to be used within the gui templates
  '#':
    material: light_blue_stained_glass_pane
    display-name: "&7"
  'P':
    material: player_head
    display-name: "<gradient:#CEB5FE:#81BAFE><bold>Profile:</bold></gradient>"
    skull-texture: mirror
    lore:
      - "&#c4f8ffDay Number: &f%rewarder_day_num%"
      - "&#c4f8ffHighest Streak: &f%rewarder_highest_streak%"
      - "&#c4f8ffMultiplier: &fx%rewarder_multiplier%"

messages:
  prefix: "<gradient:#CEB5FE:#81BAFE><bold>Rewards</bold></gradient> &8» "
  reload: "&#b7faa2ActivityRewarder has been reloaded &#66b04f🔃"
  reminder: "%prefix% &#ffe27aIt looks like you haven't collected today's reward from &#ffc940/rewards"
  daily-reward-given: "&#b7faa2You have collected today's daily reward"
  daily-playtime-reward-given: "&#b7faa2You have collected your rewards for playing &#66b04f%minutes% &#b7faa2minutes"
  global-playtime-reward-given: "&#b7faa2You have collected your rewards for playing &#66b04f%minutes% &#b7faa2minutes"
  reset-days: "&#ffe27aAre you sure you want to reset &#e0c01b%target%'s &#ffe27adays? Type &#e0c01b'/rewards reset-days %target% confirm' &#ffe27ato confirm"
  set-days: "&#ffe27aAre you sure you want to set &#e0c01b%target%'s &#ffe27adays? Type &#e0c01b'/rewards set-days %target% %streak% confirm' &#ffe27ato confirm"
  set-days-confirm: "&#66b04f%target%'s &#b7faa2day number has been set to &#66b04f%streak%"
  reset-streak: "&#ffe27aAre you sure you want to reset &#e0c01b%target%'s &#ffe27astreak? Type &#e0c01b'/rewards reset-streak %target% confirm' &#ffe27ato confirm"
  set-streak: "&#ffe27aAre you sure you want to set &#e0c01b%target%'s &#ffe27astreak? Type &#e0c01b'/rewards set-streak %target% %streak% confirm' &#ffe27ato confirm"
  set-streak-confirm: "&#66b04f%target%'s &#b7faa2streak has been set to &#66b04f%streak%"
  unknown-player: "&#ff6969Could not find &#d13636%player%"
  no-permissions: "&#ff6969Insufficient permissions"
  incorrect-usage: "&#ff6969Incorrect usage try &#d13636%command-usage%"

# Debug Modes: none, daily, playtime, all
debug-mode: none