# Placeholders:
# %day% - The day number a user is on

messages:
  reload: "&aConfig reloaded"
  reminder: "&e&lRewards &8» &7It looks like you haven't collected today's reward from &e/rewards"
  reward-given: "&e&lRewards &8» &aYou have collected today's reward"
  hourly-bonus-given: "&e&lRewards &8» &7You have received a bonus for playing &e%hours% &7hours"

gui:
  title: "&8&lDaily Rewards"
  # row-count does not include the borders, you can have a maximum of 4 rows
  row-count: 1
  upcoming-reward:
    # Whether the next "large" reward will be shown in the gui
    enabled: true
    # The slot where the reward will be displayed in the gui (Negative numbers go backwards from the end of the gui)
    slot: -5
  redeemable-name: "&6Day %day%"
  collected-name: "&6Day %day% - Collected"
  border-item: "GRAY_STAINED_GLASS_PANE"

# The number of days before the reward cycle loops
loop-length: 14
# The length in seconds between reminders being sent
reminder-period: 1800
# Whether days are going to infinitely increase or reset after loop finishes
days-reset: false

# Display items for different reward sizes
sizes:
  small: GOLD_NUGGET
  medium: GOLD_INGOT
  large: GOLD_BLOCK


# Display item for when a reward is collected
collected-item: COAL

# Placeholders:
#   %user% - The user being given the reward
#   %hourly-amount% - Number of hours multiplied by count

# Items given daily based on the amount of play time since rewards were last collected
hourly-bonus:
  default:
    rewards:
      multiplier: 1
      items:
        iron_ingot:
          amount: 2
  rank1:
    rewards:
      multiplier: 2
      items:
        diamond:
          amount: 1

# List of rewards
reward-days:
  default:
    size: SMALL
    rewards:
      items:
        cactus:
          amount: 12
        cookie:
          amount: 1
  '1':
    size: SMALL
    rewards:
      items:
        pink_tulip:
          amount: 1
        cookie:
          amount: 1
  '2':
    size: SMALL
    rewards:
      items:
        oxeye_daisy:
          amount: 1
        bread:
          amount: 1
  '5':
    size: SMALL
    rewards:
      items:
        white_tulip:
          amount: 1
        pearlescent_froglight:
          amount: 1
  '30':
    rewards:
      size: LARGE
      items:
        diamond:
          amount: 3
        golden_apple:
          amount: 1
      commands:
        - give %user% minecraft:diamond_block
        - give %user% minecraft:iron_block