messages:
  reload: "&aConfig reloaded"
  reminder: "&e&lRewards &8» &7It looks like you haven't collected today's reward from &e/rewards"
  reward-given: "&e&lRewards &8» &aYou have collected today's reward"
  hourly-bonus-given: "&e&lRewards &8» &7You have received a bonus for playing &e%hours% &7hours"

gui:
  title: "&8&lDaily Rewards"
  # Available templates: DEFAULT, COMPACT, BORDERED_DAILY, DAILY_REWARDS_PLUS, NDAILY_REWARDS, CUSTOM
  # Read https://dave-12.gitbook.io/activity-rewarder/configuring/gui-and-templates#custom-templates for more info on
  # creating and using templates
  template: "DEFAULT"
  upcoming-reward:
    # Whether the next "large" reward will be shown in the gui
    enabled: true
    # The lore of the upcoming reward (set first line to blank for item's original lore)
    lore:
      - "&7&o- Next large reward"
  # redeemable-name and collected-name can contain %day% which will display the day number related to the tiem
  redeemable-name: "&6Day %day%"
  collected-name: "&6Day %day% - Collected"
  # Display item for the border
  border-item: GRAY_STAINED_GLASS_PANE
  # Display item for when a reward is collected
  collected-item: COAL

# The number of days before the reward cycle loops
loop-length: 14
# The length in seconds between reminders being sent
reminder-period: 1800
# Whether a player's days will reset if they miss a day
days-reset: false

# Display items for different reward sizes
sizes:
  small: GOLD_NUGGET
  medium: GOLD_INGOT
  large: GOLD_BLOCK


# Placeholders:
#   %user% - The user being given the reward
#   %hourly-amount% - Number of hours multiplied by count

# Items given daily based on the amount of play time since rewards were last collected
hourly-bonus:
  # enabled: Whether hourly bonuses should be handed out
  enabled: true
  # Each section within the hourly-bonus is its own group, to give a player access to
  # a group you must give them "activityrewarder.bonus.groupName"
  #
  # For example: activityrewarder.bonus.rank1
  default:
    rewards:
      multiplier: 1
      items:
        iron_ingot:
          amount: 2
  rank1:
    rewards:
      multiplier: 2
      items:
        diamond:
          amount: 1

# List of rewards
reward-days:
  default:
    size: SMALL
    lore:
      - "&7Rewards:"
      - "&7&o-12 Cactus"
      - "&7&o-1 Cookie"
    rewards:
      items:
        cactus:
          amount: 12
        cookie:
          amount: 1
  '1':
    size: SMALL
    lore:
      - "&7Rewards:"
      - "&7&o-1 Pink Tulip"
      - "&7&o-1 Cookie"
    rewards:
      items:
        pink_tulip:
          amount: 1
        cookie:
          amount: 1
  '2':
    size: SMALL
    lore:
      - "&7Rewards:"
      - "&7&o-1 Oxeye Daisy"
      - "&7&o-1 Bread"
    rewards:
      items:
        oxeye_daisy:
          amount: 1
        bread:
          amount: 1
  '5':
    size: SMALL
    lore:
      - "&7Rewards:"
      - "&7&o-1 White Tulip"
      - "&7&o-1 Pearlescent Froglight"
    rewards:
      items:
        white_tulip:
          amount: 1
        pearlescent_froglight:
          amount: 1
  '30':
    size: LARGE
    lore:
      - "&6Rewards:"
      - "&6&o-3 Diamond"
      - "&6&o-1 Golden Apple"
    rewards:
      items:
        diamond:
          amount: 3
        golden_apple:
          amount: 1
      commands:
        - "give %user% minecraft:diamond_block"
        - "give %user% minecraft:iron_block"

# Debug Modes: none, hourly, daily, all
debug-mode: none