# Whether the daily rewards module is enabled
daily-rewards-enabled: true
# Whether the hourly rewards module is enabled
hourly-rewards-enabled: true

# Whether players will receive all rewards on a day or just the one with the highest priorty
allow-reward-stacking: false

# Whether rewards will automatically refresh when the day ticks over
# - This allows the plugin to use less ram by only storing rewards that could be needed on the specified day
rewards-refresh-daily: false

# The length in seconds between reminders being sent
reminder-period: 1800
# Whether a player will reset to day 1 if they miss a day
streak-mode: true

# Display items for different reward categories
categories:
  small:
    material: gold_nugget
  medium:
    material: gold_ingot
  large:
    material: gold_block

# Upcoming category to display
upcoming-category: large

# Display item templates
item-templates:
  # Template for default rewards
  default-reward:
    display-name: "&6Day %day%"
  # Template for collectable rewards
  redeemable-reward:
    display-name: "&6Day %day% - Redeemable"
    enchanted: true
  # Template for collected rewards
  collected-reward:
    material: coal
    display-name: "&6Day %day% - Collected"
    enchanted: false
  # Template for missed rewards
  missed-day-reward:
    material: gray_wool
    display-name: "&7Day %day% &8(Missed)"
  # Template for upcoming reward
  upcoming-reward:
    lore:
      - "&7&o- Upcoming reward"

  # Template for border item - more items can be created like this to be used within the gui templates
  '#':
    material: gray_stained_glass_pane
    display-name: "&7"
  # Template for profile item
  'P':
    material: player_head
    display-name: "&d&lProfile:"
    skull-texture: mirror
    lore:
      - "&eDay Number: &f%rewarder_day_num%"
      - "&eHighest Streak: &f%rewarder_highest_streak%"
      - "&eMultiplier: &fx%rewarder_multiplier%"

gui:
  title: "&8&lDaily Rewards"
  # Available templates: DEFAULT, COMPACT, BORDERED_DAILY, DAILY_REWARDS_PLUS, NDAILY_REWARDS, CUSTOM
  # Read https://dave-12.gitbook.io/activity-rewarder/configuring/gui-and-templates#custom-templates for more info on
  # creating and using templates
  template: "DEFAULT"

messages:
  reload: "&aConfig reloaded"
  reminder: "&e&lRewards &8» &7It looks like you haven't collected today's reward from &e/rewards"
  daily-reward-given: "&e&lRewards &8» &aYou have collected today's reward"
  hourly-reward-given: "&e&lRewards &8» &7You have received a bonus for playing &e%hours% &7hours"
  reset-streak: "Are you sure you want to reset %target%'s streak? Type '/rewards reset-streak %target% confirm' to confirm"
  set-streak: "Are you sure you want to set %target%'s streak? Type '/rewards set-streak %target% %streak% confirm' to confirm"
  set-streak-confirm: "Set %target%'s streak to %streak%"
  no-permissions: "&cInsufficient permissions"
  incorrect-usage: "&cIncorrect usage, try %command-usage%"

# Debug Modes: none, hourly, daily, all
debug-mode: none