name: ActivityRewarder
version: ${project.version}
main: me.dave.activityrewarder.ActivityRewarder
api-version: 1.19
softdepend: [floodgate]
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards