name: ActivityRewarder
version: ${project.version}
main: org.enchantedskies.activityrewarder.ActivityRewarder
api-version: 1.16
softdepend: [floodgate]
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards