name: ActivityRewarder
version: ${project.version}
main: me.dave.activityrewarder.ActivityRewarder
api-version: 1.19
softdepend: [floodgate]
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards
permissions:
  activityrewarder.use:
    description: Allows you to use the ActivityRewarder plugin
    default: true