name: LushRewards
version: ${project.version}
main: me.dave.lushrewards.LushRewards
api-version: 1.16
softdepend:
- floodgate
- MiniPlaceholders
- MythicDungeons # Fixes incompatibility
- PlaceholderAPI
folia-supported: true
modrinth-project-slug: lush-rewards
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards
    aliases:
    - lushrewards
permissions:
  lushrewards.use:
    description: Allows you to use the LushRewards plugin
    default: true
  lushrewards.reload:
    description: Allows you to reload the LushRewards plugin
    default: op