name: LushRewards
version: ${project.version}
main: org.lushplugins.lushrewards.LushRewards
api-version: 1.16
softdepend:
- floodgate
- MiniPlaceholders
- MythicDungeons # Fixes incompatibility
- PlaceholderAPI
folia-supported: true
modrinth-project-id: djC8I9ui
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards
    aliases:
    - lushrewards
permissions:
  lushrewards.use:
    description: Allows player to use the LushRewards plugin
    default: true
  lushrewards.use.*:
    description: Allows player to use a specific LushRewards module
    default: true
  lushrewards.reload:
    description: Allows player to reload the LushRewards plugin
    default: op