name: ActivityRewarder
version: ${project.version}
main: me.dave.activityrewarder.ActivityRewarder
api-version: 1.16
softdepend: [floodgate, PlaceholderAPI]
folia-supported: true
commands:
  rewards:
    description: Opens Rewards GUI
    usage: /rewards
permissions:
  activityrewarder.use:
    description: Allows you to use the ActivityRewarder plugin
    default: true
  activityrewarder.reload:
    description: Allows you to reload the ActivityRewarder plugin
    default: op